apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
  namespace: api
immutable: false
type: Opaque
data:
  postgresuri: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlcy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL215ZGI/c3NsbW9kZT1kaXNhYmxl
  redisuri: cmVkaXMtc2VydmljZXMucmVkaXMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==

