apiVersion: v1
kind: Service
metadata:
  name: postgres-services
  namespace: postgres
spec:
  clusterIP: None # Headless service
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432